apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "cdh5142cm-persistent"
spec:
  app: cdh5142cm
  roles:
  - id: controller
    resources:
      requests:
        memory: "16Gi"
        cpu: "2"
      limits:
        memory: "16Gi"
        cpu: "2"
    storage:
      size: "200Gi"
  - id: worker
    members: 2
    resources:
      requests:
        memory: "8Gi"
        cpu: "2"
      limits:
        memory: "8Gi"
        cpu: "2"
    storage:
      size: "200Gi"
