apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "tensorflow-gpu-jupyter"
spec:
  app: tensorflow-gpu-jupyter
  roles:
  - id: controller
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: "1"        
      limits:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu: "1"